In [10]:
import numpy as np
import scipy

In [173]:
class LogisticRegression_bin():
    def __init__(self, Max_iter, learning_rate, weight = None, intercept=None):
        self.Max_iter = Max_iter
        self.weight = weight
        self.intercept = intercept
        self.learning_rate = learning_rate
        
    def weight_initial(self, Xshape):
        self.weight = np.zeros(Xshape[1])
        self.intercept = 0
        
        return self.weight, self.intercept
    
    def sigmoid(self, w, x, b):
        func = 1 / (1 + np.exp(x.dot(w.transpose()) + b))
        return func
    
    def loss_grad(self, X, y, learning_rate):
        self.weight, self.intercept = self.weight_initial(X.shape)
        #we use stochatic gradient here
        #how to do stochastic gradient descent
        #initialize Loss
        
        
        for i in range(self.Max_iter):
            idxes = np.arange(len(y))
            np.random.shuffle(idxes)
            for idx in idxes:
                grad_w = (-1) * (y[idx] - self.weight.transpose().dot(X[idx]) - self.intercept) * X[idx] * self.learning_rate
                grad_b = (-1) * (y[idx] - self.weight.transpose().dot(X[idx]) - self.intercept) * self.learning_rate
                self.weight -=grad_w
                self.intercept -= grad_b
            Loss = -np.sum(y[idx] * np.log(self.sigmoid(self.weight, X, self.intercept)) + (1-y[idx]) * np.log(1-self.sigmoid(self.weight, X, self.intercept))) / X.shape[0]
            if(i % 100 == 0):
                print("loss of the func is:", Loss)
            
        return self.weight, self.intercept
    
    def fit(self, X, y):
        self.weight, self.intercept = self.loss_grad(X, y, self.learning_rate)
        
        
    def predict(self, X):
        
        y_pred = X.dot(self.weight.transpose()) + self.intercept
        y_pred[y_pred > 0.5] = 1
        y_pred[y_pred < 0.5] = 0
        
        return y_pred
    
    def score(self, y_true, y_pred):
        return np.sum(y_true == y_pred)/ len(y_true)
    

## A test Case

In [182]:
from sklearn.datasets import make_classification

X, y = make_classification(n_samples = 100, n_features=2, n_informative = 2, n_redundant=0, n_classes=2)

In [61]:
from sklearn.preprocessing import StandardScaler

In [183]:
X = StandardScaler().fit_transform(X)

In [192]:
Logist = LogisticRegression_bin(Max_iter=1000, learning_rate=0.001)

In [193]:
Logist

In [ ]:
Logist.fit(X, y)

In [195]:
Logist.predict(X)

array([1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       1., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1.,
       1., 1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1., 1.,
       1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0.,
       0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1.])

In [196]:
Logist.score(y, Logist.predict(X))

0.93

In [197]:
Logist.weight

array([ 0.44783361, -0.11487274])

In [198]:
Logist.intercept

0.4900104523098505

In [199]:
X.shape

(100, 2)

In [200]:
X[1]

array([0.49512225, 1.4235143 ])